title: Guanlin Li's homepage
logo: /figures/asu_math_campus.jpg
description: School of Mathematical and Statistical Sciences, Arizona State University 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
# https://github.com/pages-themes/minimal <- this is the source code that build the web
