title: Guanlin Li
logo: /figures/head_professional.JPG
description: ASU Spring 2016 Commencement
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
# https://github.com/pages-themes/minimal <- this is the source code that build the web
