title: Guanlin's homepage
logo: /figures/head_cute.JPG
description: ASU Spring 2016 Commencement
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
# https://github.com/pages-themes/minimal <- this is the source code that build the web
