title: Guanlin's homepage
logo: /figures/asu_pitchfork_gold_maroon_gold.png
description: ASU Spring 2016 Commencement
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
# https://github.com/pages-themes/minimal <- this is the source code that build the web
